config/routes.rb
SocialSitesIdentity::Application.routes.draw do
  resources :educations

  resources :work_positions

  resources :friends_connections

=begin  
  get "users/index"
  get "users/show"
  get "users/edit"
  get "users/update"
  get "users/destroy"
=end

  resources :users

  
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/auth/:provider/callback' => 'user_oauth#create', :as => :callback
  match '/auth/failure' => 'user_oauth#failure', :as => :failure
 
  match '/auth/facebook' => 'user_oauth#create', :as => :fb_login
  match '/auth/linkedin' => 'user_oauth#create', :as => :linkedin_login

   root :to => 'home#index'

end

app/models/friends_connection.rb
class FriendsConnection < ActiveRecord::Base
  belongs_to :user, :foreign_key => 'user_id', :class_name => 'User'
  belongs_to :user_friend, :foreign_key => 'friend_with', :class_name => 'User'
  has_many :work_positions, :foreign_key => 'friends_connection_uid'
  
  #save user's friends/connections - this method is used already first time, when is user logged in
  def self.create_new(cur_user)
    case cur_user.provider
      when 'facebook'        
        facebook_user = FbGraph::User.new(cur_user.facebook_uid, :access_token => cur_user.oauth_token).fetch

          facebook_user.friends.each do |friend| #save friends of user, who is logged-in
            begin
              remote_profile = FbGraph::User.fetch(friend.identifier, :access_token => cur_user.oauth_token)
          
              saved_fr = User.create_fb_friend(cur_user, remote_profile)
              #saving "my friends" - association
              self.create({
                :user_id => cur_user.id,
                :friend_with => saved_fr.id
              })

              #save friends work history
              remote_profile.work.each do |work_pos|
                WorkPosition.create({
                  :user_id => saved_fr.id,
                  :position => work_pos.employer.name
                })
              end
            
              #save friends work history  
              remote_profile.education.each do |edu|
                Education.create({              
                  :user_id => saved_fr.id,
                  :school => edu.school.name.downcase,
                  :start_year => nil,
                  :end_year => nil
                })
              end  
            rescue => e #handling exception
              puts e.message  
            end #exception  
          end
        
        WorkPosition.my_create_new(cur_user) #save work history of user, who is logged-in
        Education.my_create_new(cur_user) #save education history of the user, who is logged-in
        
      when 'linkedin'
        linkedin = LinkedIn::Client.new('ti57m4brxgf2', 'FqPh4FLHr2C0e3gh') 
        linkedin.authorize_from_access(cur_user.oauth_token, cur_user.oauth_secret)
        lin_user = linkedin.profile(:id => cur_user.linkedin_uid, :fields => [:date_of_birth, :main_address, :connections])
        
        User.update_all({:birth => (User.linkedin_birth(lin_user.date_of_birth) if lin_user.date_of_birth),
                         :location => lin_user.main_address},
                        {:id => cur_user.id})

        lin_user.connections.all.each do |item| #save connections of user, who is logged-in
          lin_conn = linkedin.profile(:id => item.id, :fields => [:id, :first_name, :last_name, :date_of_birth, :main_address, :public_profile_url, :educations, :positions])

          saved_conn = User.create_lin_friend(cur_user, lin_conn)

          #saving "my friends" - association
          self.create({
            :user_id => cur_user.id,
            :friend_with => saved_conn.id
          })
          
          #save connection's work position
          lin_conn.educations.all.each do |edu|
            Education.create({
              :user_id => saved_conn.id,
              :school => edu.school_name.downcase,
              :start_year => nil,
              :end_year => nil
            })
          end
          
          #save connection's work position
          lin_conn.positions.all.each do |work|
            WorkPosition.create({
              :user_id => saved_conn.id,
              :position => work.company.name.downcase
            })
          end
        end
        WorkPosition.my_create_new(cur_user) #save work history of the user, who is logged-in
        Education.my_create_new(cur_user) #save education history of the user, who is logged-in
    end
  end
  
  def self.find_mutual_friend(fb_user, lin_friend)
    find_friend = self.where('first_name = ? AND last_name = ? AND user_id = ?', lin_friend.first_name, lin_friend.last_name, fb_user.id).first
    return find_friend
  end
end

app/controllers/friends_connections_controller.rb
class FriendsConnectionsController < ApplicationController
  # GET /friends_connections
  # GET /friends_connections.json
  def index
    @friends_connections = FriendsConnection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friends_connections }
    end
  end

  # GET /friends_connections/1
  # GET /friends_connections/1.json
  def show
    @friends_connection = FriendsConnection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friends_connection }
    end
  end

  # GET /friends_connections/new
  # GET /friends_connections/new.json
  def new
    @friends_connection = FriendsConnection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friends_connection }
    end
  end

  # GET /friends_connections/1/edit
  def edit
    @friends_connection = FriendsConnection.find(params[:id])
  end

  # POST /friends_connections
  # POST /friends_connections.json
  def create
    @friends_connection = FriendsConnection.new(params[:friends_connection])

    respond_to do |format|
      if @friends_connection.save
        format.html { redirect_to @friends_connection, notice: 'Friends connection was successfully created.' }
        format.json { render json: @friends_connection, status: :created, location: @friends_connection }
      else
        format.html { render action: "new" }
        format.json { render json: @friends_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friends_connections/1
  # PUT /friends_connections/1.json
  def update
    @friends_connection = FriendsConnection.find(params[:id])

    respond_to do |format|
      if @friends_connection.update_attributes(params[:friends_connection])
        format.html { redirect_to @friends_connection, notice: 'Friends connection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friends_connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends_connections/1
  # DELETE /friends_connections/1.json
  def destroy
    @friends_connection = FriendsConnection.find(params[:id])
    @friends_connection.destroy

    respond_to do |format|
      format.html { redirect_to friends_connections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/friends_connections_helper.rb
module FriendsConnectionsHelper
end

app/views/friends_connections/_form.html.haml
= form_for @friends_connection do |f|
  -if @friends_connection.errors.any?
    #error_explanation
      %h2= "#{pluralize(@friends_connection.errors.count, "error")} prohibited this friends_connection from being saved:"
      %ul
        - @friends_connection.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :uid
    = f.text_field :uid
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :username
    = f.text_field :username
  .actions
    = f.submit 'Save'

app/views/friends_connections/edit.html.haml
%h1 Editing friends_connection

= render 'form'

= link_to 'Show', @friends_connection
\|
= link_to 'Back', friends_connections_path

app/views/friends_connections/index.html.haml
%h1 Listing friends_connections

%table
  %tr
    %th User
    %th Uid
    %th Name
    %th First name
    %th Last name
    %th Username
    %th
    %th
    %th

  - @friends_connections.each do |friends_connection|
    %tr
      %td= friends_connection.user_id
      %td= friends_connection.uid
      %td= friends_connection.name
      %td= friends_connection.first_name
      %td= friends_connection.last_name
      %td= friends_connection.username
      %td= link_to 'Show', friends_connection
      %td= link_to 'Edit', edit_friends_connection_path(friends_connection)
      %td= link_to 'Destroy', friends_connection, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Friends connection', new_friends_connection_path

app/views/friends_connections/new.html.haml
%h1 New friends_connection

= render 'form'

= link_to 'Back', friends_connections_path

app/views/friends_connections/show.html.haml
%p#notice= notice

%p
  %b User:
  = @friends_connection.user_id
%p
  %b Uid:
  = @friends_connection.uid
%p
  %b Name:
  = @friends_connection.name
%p
  %b First name:
  = @friends_connection.first_name
%p
  %b Last name:
  = @friends_connection.last_name
%p
  %b Username:
  = @friends_connection.username

= link_to 'Edit', edit_friends_connection_path(@friends_connection)
\|
= link_to 'Back', friends_connections_path