config/routes.rb
SocialSitesIdentity::Application.routes.draw do
  resources :educations

  resources :work_positions

  resources :friends_connections

=begin  
  get "users/index"
  get "users/show"
  get "users/edit"
  get "users/update"
  get "users/destroy"
=end

  resources :users

  
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/auth/:provider/callback' => 'user_oauth#create', :as => :callback
  match '/auth/failure' => 'user_oauth#failure', :as => :failure
 
  match '/auth/facebook' => 'user_oauth#create', :as => :fb_login
  match '/auth/linkedin' => 'user_oauth#create', :as => :linkedin_login

   root :to => 'home#index'

end

app/models/work_position.rb
class WorkPosition < ActiveRecord::Base
  belongs_to :friends_connection, :foreign_key => 'friends_connection_uid'
  belongs_to :user

  #method for saving work history of user, who is log-in
  def self.my_create_new(cur_user)
    case cur_user.provider
      when 'facebook' 
        my_account = FbGraph::User.new(cur_user.facebook_uid, :access_token => cur_user.oauth_token).fetch
        my_account.work.each do |position|
          self.create({
            :user_id => cur_user.id,
            :position => position.employer.name.downcase
          })
        end
        
      when 'linkedin'
        linkedin = LinkedIn::Client.new('ti57m4brxgf2', 'FqPh4FLHr2C0e3gh') 
        linkedin.authorize_from_access(cur_user.oauth_token, cur_user.oauth_secret)
        user = linkedin.profile(:fields => %w(positions))
        user.positions.all.each do |work|
          self.create({
            :user_id => cur_user.id,
            :position => work.company.name.downcase
          })
        end      
    end
  
  end
end

app/controllers/work_positions_controller.rb
class WorkPositionsController < ApplicationController
  # GET /work_positions
  # GET /work_positions.json
  def index
    @work_positions = WorkPosition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @work_positions }
    end
  end

  # GET /work_positions/1
  # GET /work_positions/1.json
  def show
    @work_position = WorkPosition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_position }
    end
  end

  # GET /work_positions/new
  # GET /work_positions/new.json
  def new
    @work_position = WorkPosition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work_position }
    end
  end

  # GET /work_positions/1/edit
  def edit
    @work_position = WorkPosition.find(params[:id])
  end

  # POST /work_positions
  # POST /work_positions.json
  def create
    @work_position = WorkPosition.new(params[:work_position])

    respond_to do |format|
      if @work_position.save
        format.html { redirect_to @work_position, notice: 'Work position was successfully created.' }
        format.json { render json: @work_position, status: :created, location: @work_position }
      else
        format.html { render action: "new" }
        format.json { render json: @work_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /work_positions/1
  # PUT /work_positions/1.json
  def update
    @work_position = WorkPosition.find(params[:id])

    respond_to do |format|
      if @work_position.update_attributes(params[:work_position])
        format.html { redirect_to @work_position, notice: 'Work position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @work_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_positions/1
  # DELETE /work_positions/1.json
  def destroy
    @work_position = WorkPosition.find(params[:id])
    @work_position.destroy

    respond_to do |format|
      format.html { redirect_to work_positions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/work_positions_helper.rb
module WorkPositionsHelper
  #print out user's work history
  def print_work_positions(user)
    wp = WorkPosition.where('user_id = ? AND friends_connection_uid IS NULL', user.id)
    if wp.count > 0
      display_wp = '<ul>'
      wp.each do |work|
        display_wp += content_tag(:li, work.position)
      end
      display_wp += '</ul>'
    else
      display_wp = '-'
    end
    display_wp.html_safe
  end
end

app/views/work_positions/_form.html.haml
= form_for @work_position do |f|
  -if @work_position.errors.any?
    #error_explanation
      %h2= "#{pluralize(@work_position.errors.count, "error")} prohibited this work_position from being saved:"
      %ul
        - @work_position.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :provider
    = f.text_field :provider
  .actions
    = f.submit 'Save'

app/views/work_positions/edit.html.haml
%h1 Editing work_position

= render 'form'

= link_to 'Show', @work_position
\|
= link_to 'Back', work_positions_path

app/views/work_positions/index.html.haml
%h1 Listing work_positions

%table
  %tr
    %th User
    %th Provider
    %th
    %th
    %th

  - @work_positions.each do |work_position|
    %tr
      %td= work_position.user_id
      %td= work_position.provider
      %td= link_to 'Show', work_position
      %td= link_to 'Edit', edit_work_position_path(work_position)
      %td= link_to 'Destroy', work_position, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Work position', new_work_position_path

app/views/work_positions/new.html.haml
%h1 New work_position

= render 'form'

= link_to 'Back', work_positions_path

app/views/work_positions/show.html.haml
%p#notice= notice

%p
  %b User:
  = @work_position.user_id
%p
  %b Provider:
  = @work_position.provider

= link_to 'Edit', edit_work_position_path(@work_position)
\|
= link_to 'Back', work_positions_path