config/routes.rb
SocialSitesIdentity::Application.routes.draw do
  resources :educations

  resources :work_positions

  resources :friends_connections

=begin  
  get "users/index"
  get "users/show"
  get "users/edit"
  get "users/update"
  get "users/destroy"
=end

  resources :users

  
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match '/auth/:provider/callback' => 'user_oauth#create', :as => :callback
  match '/auth/failure' => 'user_oauth#failure', :as => :failure
 
  match '/auth/facebook' => 'user_oauth#create', :as => :fb_login
  match '/auth/linkedin' => 'user_oauth#create', :as => :linkedin_login

   root :to => 'home#index'

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :user

  #method for saving education history of user, who is logged-in
  def self.my_create_new(cur_user)
    case cur_user.provider
      when 'facebook'       
        my_account = FbGraph::User.new(cur_user.facebook_uid, :access_token => cur_user.oauth_token).fetch
        my_account.education.each do |edu|
          self.create({
            :user_id => cur_user.id,
            :school => edu.school.name.downcase,
            :start_year => nil,
            :end_year => nil
          })
        end
        
      when 'linkedin'
        linkedin = LinkedIn::Client.new('ti57m4brxgf2', 'FqPh4FLHr2C0e3gh') 
        linkedin.authorize_from_access(cur_user.oauth_token, cur_user.oauth_secret)
        user = linkedin.profile(:fields => %w(educations))
        user.educations.all.each do |edu|
          self.create({
            :user_id => cur_user.id,
            :school => edu.school_name.downcase,
            :start_year => edu.start_date.year,
            :end_year => edu.end_date.year
          })
        end        
    end
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @educations }
    end
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
    @education = Education.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/new
  # GET /educations/new.json
  def new
    @education = Education.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/1/edit
  def edit
    @education = Education.find(params[:id])
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(params[:education])

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render json: @education, status: :created, location: @education }
      else
        format.html { render action: "new" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /educations/1
  # PUT /educations/1.json
  def update
    @education = Education.find(params[:id])

    respond_to do |format|
      if @education.update_attributes(params[:education])
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education = Education.find(params[:id])
    @education.destroy

    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
  #print out the list of user's schools
  def print_schools(user)
    if user.educations.count > 0
      display_edu = '<ul>'
      user.educations.each do |edu|
        display_edu += content_tag(:li, edu.school)
      end
      display_edu += '</ul>'
    else
      display_edu = '-'
    end
    display_edu.html_safe
  end
end

app/views/educations/_form.html.haml
= form_for @education do |f|
  -if @education.errors.any?
    #error_explanation
      %h2= "#{pluralize(@education.errors.count, "error")} prohibited this education from being saved:"
      %ul
        - @education.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :school
    = f.text_field :school
  .field
    = f.label :year
    = f.number_field :year
  .actions
    = f.submit 'Save'

app/views/educations/edit.html.haml
%h1 Editing education

= render 'form'

= link_to 'Show', @education
\|
= link_to 'Back', educations_path

app/views/educations/index.html.haml
%h1 Listing educations

%table
  %tr
    %th User
    %th School
    %th Year
    %th
    %th
    %th

  - @educations.each do |education|
    %tr
      %td= education.user_id
      %td= education.school
      %td= education.year
      %td= link_to 'Show', education
      %td= link_to 'Edit', edit_education_path(education)
      %td= link_to 'Destroy', education, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Education', new_education_path

app/views/educations/new.html.haml
%h1 New education

= render 'form'

= link_to 'Back', educations_path

app/views/educations/show.html.haml
%p#notice= notice

%p
  %b User:
  = @education.user_id
%p
  %b School:
  = @education.school
%p
  %b Year:
  = @education.year

= link_to 'Edit', edit_education_path(@education)
\|
= link_to 'Back', educations_path